
on: [push]

name: example

jobs:
  att:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@master
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: et00
        namespace: marksmith3981274
        timeout: 8m
